//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class article
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public article()
        {
            this.article_has_ingredient = new HashSet<article_has_ingredient>();
            this.order_has_articles = new HashSet<order_has_articles>();
            this.rating = new HashSet<rating>();
            this.package = new HashSet<package>();
        }
    
        public System.Guid article_id { get; set; }
        public string description { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<bool> creation { get; set; }
        public Nullable<bool> visible { get; set; }
        public System.Guid shape_id { get; set; }
        public System.Guid article_type_id { get; set; }
    
        public virtual article_type article_type { get; set; }
        public virtual shape shape { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<article_has_ingredient> article_has_ingredient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_has_articles> order_has_articles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rating> rating { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<package> package { get; set; }
    }
}
