//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class article_has_ingredient
    {
        public System.Guid article_id { get; set; }
        public System.Guid ingredient_id { get; set; }
        public Nullable<double> amount { get; set; }
    
        public virtual article article { get; set; }
        public virtual ingredient ingredient { get; set; }
    }
}
