//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class business_customer
    {
        public string VAT_Nr { get; set; }
        public string description { get; set; }
        public System.Guid person_id { get; set; }
    
        public virtual person person { get; set; }
    }
}
