//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ingredient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ingredient()
        {
            this.article_has_ingredient = new HashSet<article_has_ingredient>();
            this.mass_has_ingredient = new HashSet<mass_has_ingredient>();
            this.category = new HashSet<category>();
        }
    
        public System.Guid ingredient_id { get; set; }
        public string description { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<bool> ing_available { get; set; }
        public string unit { get; set; }
        public string path { get; set; }
        public Nullable<System.Guid> fk_ingredient_type_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<article_has_ingredient> article_has_ingredient { get; set; }
        public virtual ingredient_type ingredient_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mass_has_ingredient> mass_has_ingredient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<category> category { get; set; }
    }
}
