//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class mass_has_ingredient
    {
        public System.Guid fk_ingredient_id { get; set; }
        public System.Guid fk_mass_id { get; set; }
        public string amount { get; set; }
    
        public virtual ingredient ingredient { get; set; }
        public virtual mass mass { get; set; }
    }
}
