//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_has_package
    {
        public System.Guid fk_package_id { get; set; }
        public System.Guid fk_order_id { get; set; }
        public Nullable<double> amount { get; set; }
    
        public virtual order order { get; set; }
        public virtual package package { get; set; }
    }
}
