//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public order()
        {
            this.order_has_articles = new HashSet<order_has_articles>();
        }
    
        public System.Guid order_id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<double> total_amount { get; set; }
        public System.Guid person_id { get; set; }
        public System.Guid voucher_id { get; set; }
        public string status { get; set; }
    
        public virtual person person { get; set; }
        public virtual voucher voucher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_has_articles> order_has_articles { get; set; }
    }
}
