//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class simeontest
    {
        public System.Guid id { get; set; }
        public Nullable<System.DateTime> startdate { get; set; }
        public Nullable<int> amount { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<bool> used { get; set; }
        public Nullable<bool> visible { get; set; }
        public string description { get; set; }
    }
}
