//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataRepository.CreateWebServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatementModel", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class StatementModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TableNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DataRepository.CreateWebServiceReference.ArrayOfString PrimaryKeyNamesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DataRepository.CreateWebServiceReference.ArrayOfString PrimaryKeyValuesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DataRepository.CreateWebServiceReference.ArrayOfString ColumnsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DataRepository.CreateWebServiceReference.ArrayOfString ValuesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string TableName {
            get {
                return this.TableNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TableNameField, value) != true)) {
                    this.TableNameField = value;
                    this.RaisePropertyChanged("TableName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public DataRepository.CreateWebServiceReference.ArrayOfString PrimaryKeyNames {
            get {
                return this.PrimaryKeyNamesField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimaryKeyNamesField, value) != true)) {
                    this.PrimaryKeyNamesField = value;
                    this.RaisePropertyChanged("PrimaryKeyNames");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public DataRepository.CreateWebServiceReference.ArrayOfString PrimaryKeyValues {
            get {
                return this.PrimaryKeyValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimaryKeyValuesField, value) != true)) {
                    this.PrimaryKeyValuesField = value;
                    this.RaisePropertyChanged("PrimaryKeyValues");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public DataRepository.CreateWebServiceReference.ArrayOfString Columns {
            get {
                return this.ColumnsField;
            }
            set {
                if ((object.ReferenceEquals(this.ColumnsField, value) != true)) {
                    this.ColumnsField = value;
                    this.RaisePropertyChanged("Columns");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public DataRepository.CreateWebServiceReference.ArrayOfString Values {
            get {
                return this.ValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.ValuesField, value) != true)) {
                    this.ValuesField = value;
                    this.RaisePropertyChanged("Values");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Sender {
            get {
                return this.SenderField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderField, value) != true)) {
                    this.SenderField = value;
                    this.RaisePropertyChanged("Sender");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CreateWebServiceReference.CreateWebServiceSoap")]
    public interface CreateWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name statementModel from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertStatement", ReplyAction="*")]
        DataRepository.CreateWebServiceReference.InsertStatementResponse InsertStatement(DataRepository.CreateWebServiceReference.InsertStatementRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertStatement", ReplyAction="*")]
        System.Threading.Tasks.Task<DataRepository.CreateWebServiceReference.InsertStatementResponse> InsertStatementAsync(DataRepository.CreateWebServiceReference.InsertStatementRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertStatementRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertStatement", Namespace="http://tempuri.org/", Order=0)]
        public DataRepository.CreateWebServiceReference.InsertStatementRequestBody Body;
        
        public InsertStatementRequest() {
        }
        
        public InsertStatementRequest(DataRepository.CreateWebServiceReference.InsertStatementRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertStatementRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DataRepository.CreateWebServiceReference.StatementModel statementModel;
        
        public InsertStatementRequestBody() {
        }
        
        public InsertStatementRequestBody(DataRepository.CreateWebServiceReference.StatementModel statementModel) {
            this.statementModel = statementModel;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertStatementResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertStatementResponse", Namespace="http://tempuri.org/", Order=0)]
        public DataRepository.CreateWebServiceReference.InsertStatementResponseBody Body;
        
        public InsertStatementResponse() {
        }
        
        public InsertStatementResponse(DataRepository.CreateWebServiceReference.InsertStatementResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertStatementResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsertStatementResult;
        
        public InsertStatementResponseBody() {
        }
        
        public InsertStatementResponseBody(string InsertStatementResult) {
            this.InsertStatementResult = InsertStatementResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CreateWebServiceSoapChannel : DataRepository.CreateWebServiceReference.CreateWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreateWebServiceSoapClient : System.ServiceModel.ClientBase<DataRepository.CreateWebServiceReference.CreateWebServiceSoap>, DataRepository.CreateWebServiceReference.CreateWebServiceSoap {
        
        public CreateWebServiceSoapClient() {
        }
        
        public CreateWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CreateWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreateWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreateWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataRepository.CreateWebServiceReference.InsertStatementResponse DataRepository.CreateWebServiceReference.CreateWebServiceSoap.InsertStatement(DataRepository.CreateWebServiceReference.InsertStatementRequest request) {
            return base.Channel.InsertStatement(request);
        }
        
        public string InsertStatement(DataRepository.CreateWebServiceReference.StatementModel statementModel) {
            DataRepository.CreateWebServiceReference.InsertStatementRequest inValue = new DataRepository.CreateWebServiceReference.InsertStatementRequest();
            inValue.Body = new DataRepository.CreateWebServiceReference.InsertStatementRequestBody();
            inValue.Body.statementModel = statementModel;
            DataRepository.CreateWebServiceReference.InsertStatementResponse retVal = ((DataRepository.CreateWebServiceReference.CreateWebServiceSoap)(this)).InsertStatement(inValue);
            return retVal.Body.InsertStatementResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DataRepository.CreateWebServiceReference.InsertStatementResponse> DataRepository.CreateWebServiceReference.CreateWebServiceSoap.InsertStatementAsync(DataRepository.CreateWebServiceReference.InsertStatementRequest request) {
            return base.Channel.InsertStatementAsync(request);
        }
        
        public System.Threading.Tasks.Task<DataRepository.CreateWebServiceReference.InsertStatementResponse> InsertStatementAsync(DataRepository.CreateWebServiceReference.StatementModel statementModel) {
            DataRepository.CreateWebServiceReference.InsertStatementRequest inValue = new DataRepository.CreateWebServiceReference.InsertStatementRequest();
            inValue.Body = new DataRepository.CreateWebServiceReference.InsertStatementRequestBody();
            inValue.Body.statementModel = statementModel;
            return ((DataRepository.CreateWebServiceReference.CreateWebServiceSoap)(this)).InsertStatementAsync(inValue);
        }
    }
}
